export const keys = [
  { label: 'C', variant: 'clear' as const },
  { label: '+/-', variant: 'op' as const },
  { label: '%', variant: 'op' as const },
  { label: '/', variant: 'op' as const },
  { label: '7', variant: 'number' as const },
  { label: '8', variant: 'number' as const },
  { label: '9', variant: 'number' as const },
  { label: '*', variant: 'op' as const },
  { label: '4', variant: 'number' as const },
  { label: '5', variant: 'number' as const },
  { label: '6', variant: 'number' as const },
  { label: '-', variant: 'op' as const },
  { label: '1', variant: 'number' as const },
  { label: '2', variant: 'number' as const },
  { label: '3', variant: 'number' as const },
  { label: '+', variant: 'op' as const },
  { label: '0', variant: 'number' as const },
  { label: '.', variant: 'number' as const },
  { label: '=', variant: 'equal' as const },
]